### PR TITLE
Update version in composer.json

### PR DESCRIPTION
**Pull request by jkavalik**
Last release missed that and now does not work through composer

### CODE REVIEW

**Comment by dereuromark** [comment]
ping @markstory 
Maybe we have to automate this. Seems like this can easily go wrong.

**Comment by dereuromark** [comment]
Or we just remove this? We usually dont do this anywhere anyway, as this is redundant data - unDRY and as mentioned highly likely to be wrong/misleading if not completely automated in the release process.

**Comment by jkavalik** [comment]
Yes, imho better to not have it in there at all.

**Comment by garas** [comment]
It could read version from `vendor/composer/installed.json` instead.

**Comment by jkavalik** [comment]
I see.. What are the alternatives?

1. keep it in there and update manually
2. remove version info
3. use some other source (possibly `vendor/composer/installed.json`)

**Comment by garas** [comment]
Version could stay if https://github.com/cakephp/phinx/wiki/Releasing-a-new-version-of-Phinx#steps-to-release-a-new-version would be automated. It is now too error prone.

**Comment by dereuromark** [comment]
@markstory Can we formalized the process here and use the suggested automation for the beginning? To take out human error as factor on most part?
All releasers should then be fully aware of this requirement.

**Comment by markstory** [comment]
For other CakePHP projects that have multi-step release processes, I've had good success with using Make to automate them. We could try something similar here.

**Comment by dereuromark** [comment]
OK
Closing then for now as we will have to come up with automation instead.

**Comment by glensc** [comment]
I use myself https://github.com/Ocramius/PackageVersions:
- - Use `ocramius/package-versions` for version info (@glensc, [#549](https://github.com/eventum/eventum/pull/549))

**Pull request closed without merging**
