### PR TITLE
Add JSON support to SQLite adapter

### LINKED ISSUE #1271: Support JSON column in SQLiteAdapter
Is there any chance of supporting JSON/JSONB column types in the SQLiteAdapter. I know Laravel's Eloquent supports them by mapping them to text which seems like a fine option to me. I'd be happy to provide a PR if you would accept such a feature.

The use case is purely for testing purposes, where I run PostgreSQL in production but want a lightweight alternative in testing. The rest of the abstraction is handled by our ORM (Yii in this case)

### PR DESCRIPTION
**Pull request by jradtilbrook**
This fixes #1271.
Adding support to the SQLite adapter for JSON columns as text fields. Leaving the usage up to the application.

### CODE REVIEW

**Comment by dereuromark** [comment]
Do we need a regression test for this maybe?

**Comment by jradtilbrook** [comment]
Sorry, I'm afraid I don't know what you mean. Can you elaborate further?

**Comment by dereuromark** [comment]
A small unit test on the SQLite adapter to show that this works and will make sure it doesnt break by accident with future refactoring then :)

**Comment by jradtilbrook** [comment]
Do you mean something as simple as adding an extra JSON column to the `testGetColumns` method to ensure no exception is thrown? Like so,
```diff
diff --git a/tests/Phinx/Db/Adapter/SQLiteAdapterTest.php b/tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
index 93313db..4879db6 100644
--- a/tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
+++ b/tests/Phinx/Db/Adapter/SQLiteAdapterTest.php
@@ -421,7 +421,8 @@ public function testGetColumns()
               ->addColumn('column12', 'boolean')
               ->addColumn('column13', 'string', ['limit' => 10])
               ->addColumn('column15', 'integer', ['limit' => 10])
-              ->addColumn('column16', 'enum', ['values' => ['a', 'b', 'c']]);
+              ->addColumn('column16', 'enum', ['values' => ['a', 'b', 'c']])
+              ->addColumn('column17', 'json');
         $pendingColumns = $table->getPendingColumns();
         $table->save();
         $columns = $this->adapter->getColumns('t');
```

**Comment by jradtilbrook** [comment]
AFAIK this is ready to go with approval from a member (@dereuromark). I'm going through my pending issues/PRs and would like to finalise all that are ready.

Will this be accepted or closed?

**Comment by lorenzo** [comment]
@jradtilbrook it would be nice to have a test showing that sqlite generates a text column when using this type.

**Comment by lorenzo** [comment]
Thanks!

**Comment by piotr-cz** [comment]
Are docs updated as well?

**Pull request merged**
