### PR TITLE
Add custom column support

### PR DESCRIPTION
**Pull request by SeinopSys**
This is a second attempt at achieving what #1144 couldn't.

This PR simply adds an `addCustomColumn` method to `Table` that skips the column type validation via the use of a `CustomColumn` class that's just a copy of the regular `Column` class for distinction.

I only have PostgreSQL installed so this might need testing in MySQL & others, but I can confirm it's working in Postgres and theoretically it should work everywhere else too.

### CODE REVIEW

**Comment by lorenzo** [comment]
This will take me a couple days to review and test locally, but it is looking good!

**Comment by SeinopSys** [comment]
One potential issue is that because of the parent-child relationship `addColumn` will "accept" a `CustomColor` instance as the first parameter, should I add in a check to prevent that?

**Comment by SeinopSys** [comment]
@lorenzo Still plan on reviewing & testing this?

**Comment by lorenzo** [comment]
Yes, sorry for the delay. I took a long holiday

**Comment by chinpei215** [comment]
I think this is a really great enhancement. I was thinking of adding the same feature. If we have this feature, people would no longer need to send pull requests, such as #1204,  #1248, #1251, and #1254, unless they want abstraction.

By the way, what about we name the method `addNativeColumn()` instead `addCustomColumn()`? For example, Doctrine has `createNativeQuery()` method.

**Comment by SeinopSys** [comment]
@lorenzo @chinpei215 Please see my updated approach. I've removed `addCustomColumn` and made a `Literal` class to use with the original `addColumn` method. I think this is a much cleaner approach overall that's easy to understand and work with.

**Comment by chinpei215** [comment]
@SeinopSys Thank you. Sounds like a good approach.

**Comment by lorenzo** [comment]
I'm very sorry for how long this took to merge, Life happened

**Comment by lorenzo** [comment]
Thanks for your contribution!

**Comment by SeinopSys** [comment]
No problem.

**Comment by corpsee** [comment]
@SeinopSys @lorenzo This request breaks tests. See: https://travis-ci.org/cakephp/phinx/jobs/372687856.

**Comment by SeinopSys** [comment]
@corpsee I find that odd considering the [last build of this PR](https://travis-ci.org/cakephp/phinx/jobs/334149431) passed before. I've no clue why it broke just now.

**Comment by SeinopSys** [comment]
Found a fix, but I cannot push here anymore.

```
diff --git a/src/Phinx/Db/Adapter/PostgresAdapter.php b/src/Phinx/Db/Adapter/PostgresAdapter.php
index 60329d9..54ffa16 100644
--- a/src/Phinx/Db/Adapter/PostgresAdapter.php
+++ b/src/Phinx/Db/Adapter/PostgresAdapter.php
@@ -362,8 +362,7 @@ public function getColumns($tableName)
                 $column->setLimit($columnInfo['character_maximum_length']);
             }
 
-            $phinxType = $this->getPhinxType($columnInfo['data_type']);
-            if (in_array($phinxType, [static::PHINX_TYPE_TIME, static::PHINX_TYPE_DATETIME])) {
+            if (in_array($columnType, [static::PHINX_TYPE_TIME, static::PHINX_TYPE_DATETIME])) {
                 $column->setPrecision($columnInfo['datetime_precision']);
             } else {
                 $column->setPrecision($columnInfo['numeric_precision']);
~
~
```

**Comment by corpsee** [comment]
@SeinopSys thank you for the details.

**Comment by lorenzo** [comment]
Can you open a new PR?

**Comment by SeinopSys** [comment]
@lorenzo #1340

**Pull request merged**
