### PR TITLE
Copyright looks changed

### PR DESCRIPTION
**Pull request by harikt**
This PR https://github.com/cakephp/phinx/pull/1119 changes Copyright. I believe this may have been missed.

### CODE REVIEW

**Comment by harikt** [comment]
@robmorgan , @lorenzo thoughts ?

**Comment by Iandenh** [comment]
I think you do not replace the name but add it. Like here: https://github.com/cakephp/chronos/blob/master/LICENSE

**Comment by harikt** [comment]
@Iandenh Thank you for the suggestion. I don't have any problem with that.

I was looking at https://github.com/cakephp/phinx/pull/1119/files#diff-85987f48f1258d9ee486e3191495582dR44 and the author @robmorgan himself changed there. I can consider changing as suggested. Let us give some time and hear what others say about the same.

Thank you.

**Comment by robmorgan** [comment]
Sorry I deliberately haven't changed the license yet, because I'm checking with @phpnut about the actual legality. I will properly have to sign some transfer paperwork first.

**Comment by harikt** [comment]
Thank you for making it clear @robmorgan .

**Comment by harikt** [comment]
May be we close this PR ?

**Comment by robmorgan** [comment]
@phpnut any ideas? should we add CakePHP alongside my name?

**Comment by dereuromark** [comment]
Closing for now.

**Pull request closed without merging**
