### PR TITLE
Postgres enum/set/double/bytea support

### PR DESCRIPTION
**Pull request by Vitexus**
This patch allow you to create tables with enum/set column types
Also added small fixes for double and bytea postgresql data types

### CODE REVIEW

**Comment by Vitexus** [comment]
I'am not sure how to make scrutinizer be successfully finished :(

**Comment by mvrhov** [comment]
At least for enum I don't like on how it's handled. As this doesn't allow you to change the enum in further updates.

**Comment by Vitexus** [comment]
Thank you for your advice. Please be patitent ill try do my best :)

**Comment by JayPHP** [comment]
@Vitexus https://github.com/cakephp/phinx/pull/743#issuecomment-172105755 do you plan to do anymore for this PR?

**Comment by Vitexus** [comment]
Not yet

**Comment by JayPHP** [comment]
@Vitexus Ok, closing this for now. Please feel free to re-open once you have some more time to work on it. Thanks for contributing :)

**Pull request closed without merging**
