### PR TITLE
index type and partial index

### PR DESCRIPTION
**Pull request by mvrhov**
* added support for partial indexes via WHERE keyword, postgresql, Sqlserver and sqlite
* added support for index type (btree, hash, gin,..) via USING keyword, postgresql, mysql feature

### CODE REVIEW

**Comment by mvrhov** [comment]
Added docs and partial's support for all DBs that support them

**Comment by mvrhov** [comment]
What's missing to get this merged?

**Comment by rquadling** [comment]
Principle looks good. It would be nice to have some tests.
Escaping/guarding of invalid values may be a good idea.

**Comment by lorenzo** [comment]
Having tests would be nice!

**Comment by mvrhov** [comment]
* Written my own migration library in this time [migratum](github.com/mvrhov/migratum)
* moving to golang

Somebody else should take over. Or this should be closed.

**Comment by lorenzo** [comment]
Closing until this can come up again in a future version

**Pull request closed without merging**
