### PR TITLE
Test against PHP 7.2

### PR DESCRIPTION
**Pull request by carusogabriel**
With the release of [`PHP 7.2`](php.net/archive/2017.php#id2017-11-30-1), would be interesting to test it.

### CODE REVIEW

**Comment by chinpei215** [comment]
Test failed.

**Comment by carusogabriel** [comment]
The method `count` now [throws an Exception if it is trying to count an non Coutable](https://wiki.php.net/rfc/counting_non_countables). Goona work on fixes.

**Comment by carusogabriel** [comment]
The `each` method was [deprecated in PHP 7.2](https://wiki.php.net/rfc/deprecations_php_7_2). I'm gonna work on PHPUnit 6 compatibility, that fixes it.

**Comment by chinpei215** [comment]
https://travis-ci.org/cakephp/phinx/jobs/314070337#L545

The error seems to be caused by the [sebastian/comparator](https://packagist.org/packages/sebastian/comparator).

**Comment by carusogabriel** [comment]
I guess after merge #1238 everything will works.

**Comment by chinpei215** [comment]
OK. I will check both patches on my local environment, and if there are no problems I will merge them.

**Comment by ADmad** [comment]
@carusogabriel PHP 7.2 build still fails after merging of #1238. Can you try rebasing your branch on top of latest master?

**Comment by carusogabriel** [comment]
@ADmad After rebase, still not working. I'm going to install `PHP 7.2` locally and try to fix it :sweat_smile:

**Comment by ADmad** [comment]
Phpunit 4 would probably be required for PHP 5.4/5.5.

**Comment by winkbrace** [comment]
@carusogabriel Have you made any progress on this? Would you like some assistance?

**Comment by winkbrace** [comment]
Nevermind, it was an easy fix in PR #1293

However, I had to specify a "fixed" minimum version of a dependency of phpunit. It feels a little odd to require a dependency of a dependency, but I don't see another solution.

**Comment by ADmad** [comment]
Closing in favor of #1293.

**Pull request closed without merging**
