### PR TITLE
Add an option to archive migration into sub-folders

### PR DESCRIPTION
**Pull request by t1gor**
We currently have about ~40 migration files and it is not handy any more to have them all in one folder.

So now, if you move the migrations [under a sub-directory](https://github.com/robmorgan/phinx/files/61359/after-move.txt), `phinx` will not be able to see them. The idea is to preserve the logic, but only add ability to check sub-directories, so the [output](https://github.com/robmorgan/phinx/files/61360/before.txt) remains the same.

Please take a look at the code and let me know your thoughts. 
Tests and PSR2 comparability checked.

### CODE REVIEW

**Comment by shadowhand** [comment]
Related to #489

**Comment by shadowhand** [comment]
Please rebase this branch to resolve conflicts. Thank you!

**Comment by t1gor** [comment]
Hi, @shadowhand. I wil as soon as I get back to the office (approximately January 4). Sorry for the delay

**Comment by t1gor** [comment]
@shadowhand rebased and fixed UT. Please take a look. Thanks!

**Comment by robmorgan** [comment]
also related to https://github.com/robmorgan/phinx/pull/736

**Comment by wandersonwhcr** [comment]
:open_mouth:

hey, if you use a `glob` pattern like `./db/migrations/{,*}`, is not the same?

**Comment by t1gor** [comment]
@wandersonwhcr it might ... but what is wrong with iterators, except that it is a longer solution?

**Comment by wandersonwhcr** [comment]
Maintenance, I think.

But you solution enable future implementation for multiple directories :+1:  .

**Comment by wandersonwhcr** [comment]
Hey @t1gor, @rquadling and I found some problems with `glob` and `phinx create`. @shadowhand just merged my PR with errors and @rquadling created a revert PR.

**Comment by t1gor** [comment]
Hi, guys. I guess I would rather create another request again ... now following the contributing notes :)

**Comment by wandersonwhcr** [comment]
I have some questions: why only subfolders? PR #742 will help you with this?

I just think we must join efforts and add this feature to multiple folders.

What do you think, people? // cc @t1gor, @shadowhand @robmorgan @danives3d, @sleg, @rquadling

**Comment by rquadling** [comment]
As a contributor, it seems there is a lot of overlap and similarities between the various outstanding PRs dealing with multiple paths and multiple DBs.

So, maybe some consolidation on the various proposals, worked into some sort of roadmap, would be useful.

Currently, Phinx operates on a single directory for migrations and operates against a single database. Multiple databases is supported by defining multiple environments, but only 1 of them is interacted with at a time.

The main requirements seem to be:
* Multiple paths for migration files.
* Allow migrations to be run against multiple environments in a single migrate/rollback call
* POTENTIALLY, multiple migration paths tuned to an environment.

Some issues/ideas/suggestions:
* Whilst creating a migration, Phinx would need to know where to place the migration file. Several options exist to cover this (a new commandline option, show a list at runtime, allow template generating classes to provide a location, etc.)
* Managing migration failures across multiple environments. Should remaining migrations on remaining environments be ran? Automatic rollback of migrations across environments that were migrated for the failing migration (e.g. server 5 of 10 failed, so rollback servers 1 to 4?).
* Should migration order by each migration across all servers or all migrations across each server?
* Viewing the status of a multiple migrations across multiple servers would require some better UI than we currently have with the straight list.
* For multiple servers, better inbuilt tracking/logging of errors to be able to see the issues after the fact rather than just as console output.

I think until there is a better understanding about when things go wrong, then we may be in a better situation to evaluate the proposals.

**Comment by t1gor** [comment]
Hi, guys.

I wanted to update this request and finally get it working in my project in a nearest future, but it seems to me that I am doing something wrong ... Below are the steps of what I did:

I've started with rebase (started from clone to get a clean copy, didn't touch it for a while)

```
git clone https://github.com/t1gor/phinx.git Phinx
git checkout feature-archive
git remote add robmorgan https://github.com/robmorgan/phinx.git
git pull
git rebase robmorgan/5.0.x-dev
git push
```

After pushing, [AppVeyor](https://ci.appveyor.com/project/robmorgan/phinx/build/1.0.1129) and [Travis](https://travis-ci.org/robmorgan/phinx/jobs/121449626) both report failed tests:

Test\Phinx\Console\PhinxApplicationTest::testRun

**Comment by rquadling** [comment]
glob() does not guarantee the order of the files on all OSs. Also, 

The difference in the messages is the order of the files.

```
Migration "20120111235331_duplicate_migration_name.php" has the same name as "20120111235330_duplicate_migration_name.php"
```
vs.
```
Migration "20120111235330_duplicate_migration_name.php" has the same name as "20120111235331_duplicate_migration_name.php"
```

Sorting the files prior to processing them (or as part of the output of the iterator) will allow the test to pass. The test is accurate and shouldn't have been modified.

The output of the test is saying that the name part of a newer migration already exists in a prior migration.

**Comment by t1gor** [comment]
@rquadling thanks for the hint with `glob()`.

**Comment by JayPHP** [comment]
Looking to close this PR soon due to it's age. If you'd like it kept open, please let me know and raise a new issue. Note - https://github.com/cakephp/phinx/pull/927

**Pull request closed without merging**
