### PR TITLE
Clear migration direction nomencalture

### PR DESCRIPTION
**Pull request by Roy-Orbison**
Remnants of (partially duplicated) changes per @mvrhov's suggestion in PR #1164.

### CODE REVIEW

**Comment by lorenzo** [comment]
Thanks!

**Comment by Roy-Orbison** [comment]
Didn't realise someone had pretty much done it.

**Comment by lorenzo** [comment]
It was me, needed it done before the 0.9.1 release :)

**Comment by mvrhov** [comment]
Thanks. I'm really really without any time to spare for OSS :/

**Pull request merged**
