### PR TITLE
migrate and rollback commands use the env options, which parses the dsn

### PR DESCRIPTION
**Pull request by watermark**
Use the parsed DSN for the migrate and rollback command #1406

### CODE REVIEW

**Comment by lorenzo** [comment]
Tests are failing, can you please fix those?

**Comment by watermark** [comment]
I updated the code to account for a null possibility, but the tests are still failing.  I think this may be a failing of the mock object (which I'm not very familiar with).  A function that should never return null is returning null due to the mocking.

**Comment by lorenzo** [comment]
I think the problem it that you needed to update the tests, it is safe to assume the manager is passed.

**Comment by dereuromark** [comment]
ping @watermark 

Are you still interested in finishing this? Would be awesome.
Otherwise, we have to close.

**Comment by othercorey** [comment]
Closing due to no activity.

**Pull request closed without merging**
