### PR TITLE
Docs about seed: Call to save() method replaced for saveData()

### PR DESCRIPTION
**Pull request by georgezim85**
Avoid error: Base table or view already exists: 1050 Table <table_name> already exists

### CODE REVIEW

**Comment by lorenzo** [comment]
hmm, this should not be the case. Can you explain how this can be reproduced?

**Comment by dereuromark** [comment]
Any update here? ping @georgezim85

**Comment by georgezim85** [comment]
> hmm, this should not be the case. Can you explain how this can be reproduced?

Sure. If you have a table already created and so you want to populate using the seeder you are creating, you cant't do it using the "save()" method, because it will try to create de table again, so we must use saveData() to just insert the data.

**Comment by georgezim85** [comment]
> > hmm, this should not be the case. Can you explain how this can be reproduced?
> 
> Sure. If you have a table already created and so you want to populate using the seeder you are creating, you cant't do it using the "save()" method, because it will try to create de table again, so we must use saveData() to just insert the data.

I am referring to MySql databases.

**Comment by lorenzo** [comment]
I see, this looks good to me now. Thanks

**Pull request merged**
