### PR TITLE
Enable PHP7.3

### PR DESCRIPTION
**Pull request by dereuromark**

### CODE REVIEW

**Comment by dereuromark** [comment]
interesting fail

**Comment by dereuromark** [comment]
Any idea of a fix here?

**Comment by garas** [comment]
PHP 7.3 is linked with newer Sqlite.

Sqlite doesn't support column comments Phinx emulates comments by appending `/* comment */` to column definition.

New Sqlite probably now handles `/* */` differently.

I suggest to skip adding emulated comment in Sqlite. 

Column changing already refuses that, it should be the same when adding column.
https://github.com/cakephp/phinx/blob/76c96c851b737f93598d7ae7765a5cd2cc99ae7a/src/Phinx/Db/Adapter/SQLiteAdapter.php#L286-L289

**Comment by dereuromark** [comment]
Help is greatly appreciated.

**Comment by dereuromark** [comment]
2nd part sounds good.
@lorenzo what do you think?

**Comment by lorenzo** [comment]
hmm, how should be getting the comments in sqlite now?

**Comment by JKingweb** [comment]
@dereuromark Can you run the checks again? The test should pass, now.

**Comment by dereuromark** [comment]
The comment issue is still there:
```
-''another default''
+''another default' /* another comment */'
```

**Comment by MasterOdin** [comment]
You probably need to merge master first.

**Comment by lorenzo** [comment]
👏

**Pull request merged**
