### PR TITLE
add row_format option to mysqladapter

### PR DESCRIPTION
**Pull request by ryoichi-u**

### CODE REVIEW

**Comment by Erwane** [comment]
Why it's abandoned ? it's a really important feature

**Comment by dereuromark** [comment]
What is abandoned?

**Comment by Erwane** [comment]
possibility to add ROW_FORMAT in Table creation options.

His merge request sounds good (except the print_r and missing quote protection)

**Comment by dereuromark** [comment]
Feel free to make an alternative PR here.

**Pull request closed without merging**
