### PR TITLE
Add version to composer.json.

### PR DESCRIPTION
**Pull request by ADmad**
Alternative to #1263

### CODE REVIEW

**Comment by saeideng** [comment]
nice 
we can add version into cakephp/app/composer.json too :)

**Comment by olybri** [comment]
I noticed that running Phinx from a Phar archive now fails to print the version since *composer.json* is not part of the archive. Adding *composer.json* into *box.json* should fix that.

**Comment by dereuromark** [comment]
Are you able to quickly fix up a PR here?

**Comment by olybri** [comment]
#1277 fixes this.

**Pull request merged**
