### PR TITLE
Make hasTable understand 'schema.tableName' notation.

### PR DESCRIPTION
**Pull request by winkbrace**
In a setup with one application using multiple mysql databases, I don't want to have to setup phinx for each database. Instead, all we have to do is make `hasTable` understand the "schema.table" notation and we're golden.

### CODE REVIEW

**Comment by dereuromark** [comment]
Can this introduce a regression for tables that might contain a dot already in their table name?
Or is this not possible so far?

**Comment by winkbrace** [comment]
My god, a dot in the table name allowed?!

So I guess that makes this change breaking for those users. Though honestly I don't expect there to be more than a handful.

The only way to be sure is to check the database meta tables then, but that can become expensive... hmm..

**Comment by winkbrace** [comment]
Since we are already checking the information schema, adding support for tables with a dot in the name was not difficult or very expensive.

When hasTable finds a dot in the table name, it will first assume "schema.table" notation and if table is not found, fall through to looking up the complete table name in the main schema.

**Comment by lorenzo** [comment]
Does this work in postgres as well? I'm not comfortable only adding support for mysql

**Comment by corpsee** [comment]
@lorenzo [There is](https://github.com/cakephp/phinx/pull/1193) support schemas for PostgreSQL (Not only for `hasTable` but for all operations for tables with schema).

**Comment by winkbrace** [comment]
Since we require this fork to use phinx, I had to rebase it on the latest stable release. So we have conflicts with master which I will resolve when you are ready to merge.

I will also look into the postgres changes and see what I have to add for mysql to make it schema aware everywhere.

**Comment by dereuromark** [comment]
Are you still interested in fixing this up?

**Comment by winkbrace** [comment]
I am happy to resolve the conflicts, but since I've moved to another project and am not using phinx anymore I suggest we merge the changes that I've made and that are enough for most use cases where multiple mysql databases are used.

At work we happily used my fork for over a year without any issues.

**Comment by lorenzo** [comment]
@winkbrace if you can resolve the conflicts, that would be great

**Comment by dereuromark** [comment]
New PR: https://github.com/cakephp/phinx/pull/1624

**Comment by winkbrace** [comment]
Thanks Arjen <3

**Pull request closed without merging**
