### PR TITLE
PDO FETCH_MODE Support

### PR DESCRIPTION
**Pull request by crona2011**
I used this and faker to seed a benchmarking database. I needed to pull from multiple tables and restructure my data. When using `fetchAll()` there is no way of specifying the PDO `FETCH_MODE`, so I added a setter and getter to your `PdoAdapter` class:

```
    /**
     * @var integer
     */
    protected $fetchMode = \PDO::FETCH_BOTH;

...

    /**
     * Gets the PDO fetch mode
     *
     * @return integer the current PDO fetch mode
     */
    public function getFetchMode()
    {
        return $this->fetchMode;
    }

    /**
     * Sets the PDO fetch mode
     *
     * @param integer PDO mode or (int) representation
     */
    public function setFetchMode($mode)
    {
        $this->fetchMode = $mode;
    }
```

Now I can use it in my seed command:
`$this -> getAdapter() -> setFetchMode(\PDO::FETCH_ASSOC);`

Take it or leave it, it was useful for me.

### CODE REVIEW

**Comment by lorenzo** [comment]
Can you rebase the branch? There seem to be more commits that what you originally intended to send

**Comment by ravage84** [comment]
I guess this needs to be rebased before it can be looked after again.

**Comment by saeideng** [comment]
@ravage84 
why you want to merge into `0.7.x-dev` from `master`
I think this is not true PR

**Comment by ravage84** [comment]
Closing due to inactivity. @crona2011 please put up a new PR towards the correct branch, if you want.

**Pull request closed without merging**
