### PR TITLE
Migration listings in \Phinx\Migration\Manager::getMigrations() are now only output in VERBOSE_DEBUG mode (-vvv).

### PR DESCRIPTION
**Pull request by rquadling**

### CODE REVIEW

**Comment by lorenzo** [comment]
Can you paste an example of the output before and after?

**Comment by rquadling** [comment]
Before (note that this is with `-v`)  ...
```
$ bin/phinx status -v
Phinx by CakePHP - https://phinx.org. 0.10.2

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /Users/richardquadling/dev/php/robmorgan/db/migrations
using seed paths 
 - /Users/richardquadling/dev/php/robmorgan/db/seeds
warning no environment specified, defaulting to: development
ordering by creation time
Migration file /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Valid migration file /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class First from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
Running First
Valid migration file /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class Second from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
Running Second
Valid migration file /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php, /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class Third from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Running Third

 Status  [Migration ID]  Started              Finished             Migration Name 
----------------------------------------------------------------------------------
     up  20120111235330  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration   ** MISSING **
     up  20120116183504  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration2  ** MISSING **
   down  20180620091443                                            First
   down  20180620091446                                            Second
   down  20180620091448                                            Third

```

After ...
```
$ bin/phinx status -vv
Phinx by CakePHP - https://phinx.org. 0.10.2

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /Users/richardquadling/dev/php/robmorgan/db/migrations
using seed paths 
 - /Users/richardquadling/dev/php/robmorgan/db/seeds
warning no environment specified, defaulting to: development
ordering by creation time

 Status  [Migration ID]  Started              Finished             Migration Name 
----------------------------------------------------------------------------------
     up  20120111235330  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration   ** MISSING **
     up  20120116183504  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration2  ** MISSING **
   down  20180620091443                                            First
   down  20180620091446                                            Second
   down  20180620091448                                            Third


$ bin/phinx status -vvv
Phinx by CakePHP - https://phinx.org. 0.10.2

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /Users/richardquadling/dev/php/robmorgan/db/migrations
using seed paths 
 - /Users/richardquadling/dev/php/robmorgan/db/seeds
warning no environment specified, defaulting to: development
ordering by creation time
Migration file
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Valid migration file
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class First from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
Running First
Valid migration file
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class Second from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
Running Second
Valid migration file
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091443_first.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091446_second.php
    /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Loading class Third from /Users/richardquadling/dev/php/robmorgan/db/migrations/20180620091448_third.php
Running Third

 Status  [Migration ID]  Started              Finished             Migration Name 
----------------------------------------------------------------------------------
     up  20120111235330  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration   ** MISSING **
     up  20120116183504  2018-06-19 16:50:34  2018-06-19 16:50:34  TestMigration2  ** MISSING **
   down  20180620091443                                            First
   down  20180620091446                                            Second
   down  20180620091448                                            Third

```

**Comment by rquadling** [comment]
I don't really see the need for any of this, but `-v` is interfering with some of the pipeline outputs. I see the output really only useful in debug mode, not just a general verbose mode.

**Comment by lorenzo** [comment]
@rquadling Yeah, this is definitely an improvement

**Pull request merged**
