### PR TITLE
Run with mysql:8.0.20

### PR DESCRIPTION
**Pull request by othercorey**

### CODE REVIEW

**Comment by dereuromark** [comment]
Shall we merge this then for now?

**Comment by othercorey** [comment]
Well, something in the `getPrimaryKey` fails in the very latest mysql8. I don't know why, but I don't know if restricting the test version is good long-term.

It's possible that 8.0.21 is simply buggy and so should be ignored -- but then we'll miss 8.0.22.

**Comment by dereuromark** [comment]
We can open a separate matrix build with the higher one and keep it allow_failure for now until we find more details on how to solve it
But having red master and red PRs is not helpful either for now.

**Comment by othercorey** [comment]
No objections. Just explaining the little I found out.

**Pull request closed without merging**
