### PR TITLE
Fix failing SQLServer tests

### PR DESCRIPTION
**Pull request by djcvijic**

### CODE REVIEW

**Comment by lorenzo** [comment]
You're a hero!

Are tests passing already for you?

**Comment by lorenzo** [comment]
@djcvijic there is this failing test you should take cake of https://travis-ci.org/cakephp/phinx/jobs/396317459

**Comment by djcvijic** [comment]
Oops!
Will do.

**Comment by djcvijic** [comment]
I don't think I can do anything about appveyor, it looks like it's some kind of build error.

**Comment by saeideng** [comment]
@djcvijic I can re-start it

**Comment by saeideng** [comment]
AppVeyor now is on

**Comment by djcvijic** [comment]
Thank you @saeideng.
But what should we do about the two remaining failing tests? They are tests that I have not touched, and I can not reproduce either of the bugs.
I'm inclined to just mark them for skipping...

**Comment by saeideng** [comment]
```php
2) Test\Phinx\Db\Adapter\SqlServerAdapterTest::testQueryBuilder
Failed asserting that -1 matches expected 2.
C:\projects\phinx\tests\Phinx\Db\Adapter\SqlServerAdapterTest.php:810
```
I think `testQueryBuilder` test should fix in this PR , or next PR

**Comment by djcvijic** [comment]
There, now there's only one failing test, the queryBuilder one. Since it actually tests an external dependency, I'm counting on you who are already familiar to fix it...

**Comment by lorenzo** [comment]
Thanks so much!

**Pull request merged**
