### PR TITLE
Custom seeder base class

### PR DESCRIPTION
**Pull request by dead23angel**
Add to config **seed_base_class**

### CODE REVIEW

**Comment by dead23angel** [comment]
I realized that was asked this query https://github.com/robmorgan/phinx/issues/773

**Comment by rquadling** [comment]
The ConfigInterface also needs this method. Which results in another minor version bump.

**Comment by dead23angel** [comment]
@rquadling, I added methods in the ConfigInterface

**Comment by rquadling** [comment]
Thanks.

**Comment by tstuttard** [comment]
Is this looking to get merged anytime soon? Currently needing this on a project I am using.

**Comment by rewchelsea** [comment]
I also need this on a project I'm working on - is this going to get merged?

**Comment by rquadling** [comment]
Hi. Things have been a little slow. Will tag this for me to look at over the weekend.

Thank you for your patience.

Some unit tests would be nice.

**Comment by dead23angel** [comment]
I also need this on a project I'm working on - is this going to get merged?

**Comment by rquadling** [comment]
I'm currently working on repeatables and I've incorporated this functionality into my branch. Not yet production ready but as I'm doing this both for Phinx and my employment, things are moving a lot faster.

Anyone wanting to clean up the PR would help the current codebase.

**Comment by dereuromark** [comment]
Looks like this can move forward then once the conflicts are resolved.

**Comment by glensc** [comment]
will attempt to resolve conflicts.

created copy of this branch for now: https://github.com/cakephp/phinx/pull/1512

**Comment by glensc** [comment]
this one can be closed, changes requested here are implemented in #1512

**Comment by glensc** [comment]
@dead23angel you can close this one in favor of https://github.com/cakephp/phinx/pull/1512

**Comment by garas** [comment]
Closing in favor of #1512

**Pull request closed without merging**
