### PR TITLE
Using `--verbose` to display raw queries.

### PR DESCRIPTION
**Pull request by dinamic**
This was requested in https://github.com/robmorgan/phinx/issues/93 and seems like a necessity when something goes wrong with the migrations. I am rather surprised it has not been implemented yet.

This functionality gives you the ability to troubleshoot custom queries using either `execute()` or `query()`. The currently implementation works only for PdoAdapter, but seems like all the other adapters are based on top of it. Should the solution get approved, I will revisit that statement and verify I am not missing any.

I am using the solution suggested by @tomzx, props to him for suggesting it!

### CODE REVIEW

**Comment by dereuromark** [comment]
Thank you for you valuable input and improvement here.

If you resolve the conflict this looks it can be merged right away.
Not sure why this was stalled for so many months - but we should fix it now.

**Comment by lorenzo** [comment]
Can we have this as an adaptor wrapper instead? Like the timer wrapper

**Comment by ravage84** [comment]
How about adding an additional parameter ``--queries`` for that specific need?
When we add too much stuff to the verbosity flag, we might need a ``-vv`` (verbose verbosity) flag one day 😼

**Comment by abekroenem** [comment]
This is a great improvement to Phinx.

I do agree with @ravage84 , this modification may need an specific argument to be called, like `--queries` or more explicit `--show-sql`, `--show-queries`.

**Comment by lorenzo** [comment]
This was implemented and already in the master branch

**Pull request closed without merging**
