### PR TITLE
Fix adding columns to existing sqlite table with table constraints

### LINKED ISSUE #1843: SQLite Memory update() errors in phpunit tests
Since version 0.12.0 I get an error when I try to migrate with an update with SQLite memory in tests phpunit.

With MySQL all works fine.

Thanks for your help

**Migration**
```
public function change(): void
    {
        $table = $this->table('posts');
        $table
            ->addColumn('image', 'string', ['null' => true])
            ->update();
    }
```
**Config**
```
$configArray = require('phinx.php');
        $configArray['environments']['test'] = [
            'adapter'    => 'sqlite',
            'connection' => $pdo
        ];
        $config = new Config($configArray);
        return new Manager($config, new StringInput(' '), new NullOutput());
```
**Migration process**
```
    public function migrateDatabase(PDO $pdo)
    {
        $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_BOTH);
        $this->getManager($pdo)->migrate('test');
        $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
    }
```
**Error in all tests where migrateDatabase(PDO $pdo) is used**
```
Test::testFind PDOException: SQLSTATE[HY000]: General error: 1 near "image": syntax error
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:185 
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\SQLiteAdapter.php:705 
...\vendor\robmorgan\phinx\src\Phinx\Db\Util\AlterInstructions.php:119 
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:619 
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:1021 
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\AdapterWrapper.php:514 
...\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\TimedOutputAdapter.php:452 
...\vendor\robmorgan\phinx\src\Phinx\Db\Plan\Plan.php:154 ...\vendor\cakephp\collection\CollectionTrait.php:69 
...\vendor\robmorgan\phinx\src\Phinx\Db\Plan\Plan.php:155 ...\vendor\robmorgan\phinx\src\Phinx\Db\Table.php:722 
...\vendor\robmorgan\phinx\src\Phinx\Db\Table.php:628 ...\src\Blog\db\migrations\20200624155215_add_image_to_post.php:36 
...\vendor\robmorgan\phinx\src\Phinx\Migration\Manager\Environment.php:109 
...\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:377 
...\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:350 ...\tests\DatabaseTestCase.php:36 
...\tests\Blog\Table\PostTableTest.php:18
```

### PR DESCRIPTION
**Pull request by MasterOdin**
If a table within sqlite had been made with table level constraints (e.g. foreign key constraint), it would then throw an exception on attempting to add any further columns. This is due to 16c83d1 appending the new column at the end of the create table SQL, after any constraints. This patch modifies it so that it will inject the new column after the last existing column, which will place it before any constraints.

Closes #1843

### CODE REVIEW

**Comment by dereuromark** [comment]
@Franco291
Can you confirm this works for you and we can tag a new bugfix release?

**Comment by Franco2911** [comment]
> @Franco2911
> Can you confirm this works for you and we can tag a new bugfix release?

Now it seems to have new errors like this one

```
6) Tests\App\Blog\Table\PostTableTest::testUpdate
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.firstname

H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:326
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\AdapterWrapper.php:180
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\TimedOutputAdapter.php:103
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Table.php:658
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Table.php:630
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Db\Table.php:688
H:\LAB\COURS GRAFIKART\GestiBlog\src\Auth\db\seeds\UserSeeder.php:16
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Migration\Manager\Environment.php:147
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:414
H:\LAB\COURS GRAFIKART\GestiBlog\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:557
H:\LAB\COURS GRAFIKART\GestiBlog\tests\DatabaseTestCase.php:45
H:\LAB\COURS GRAFIKART\GestiBlog\tests\Blog\Table\PostTableTest.php:41
```

**Comment by MasterOdin** [comment]
Could you share the migrations and table definition that's causing this?

**Comment by Franco2911** [comment]
> Could you share the migrations and table definition that's causing this?

The migrations are in #1843
If I understand this error correctly, it seems that the fields are not nullable by default when creating columns.

**Comment by MasterOdin** [comment]
Yes, columns are `NOT NULL` by default. SQLite, prior to 0.12, had a different logic for determining default not null than other adapters, which is why this worked previously, but on 0.12, it was made consistent with everybody else, which is to default to `not null` unless you explicitly specify `'null' => false` in your column options.

There is https://github.com/cakephp/phinx/issues/1817 to change that behavior to be the inverse (default to `null`), which will probably land in 0.13 whenever that might release.

**Comment by Franco2911** [comment]
Ok, I just did one last test and the error is from the null field. if I add columns without ['null' => true] the error occurs if i add it there are no more errors. 100% test ok.

**migration error**
```
public function change(): void
    {
        $this->table('users')
            ->addColumn('firstname', 'string')
            ->addColumn('lastname', 'string')
            ->update();
    }
```
**Migration without any error**
```
public function change(): void
    {
        $this->table('users')
            ->addColumn('firstname', 'string', ['null' => true])
            ->addColumn('lastname', 'string', ['null' => true])
            ->update();
    }
```

**Comment by MasterOdin** [comment]
Alright, cool. So I think we can reclose #1843 (@dereuromark) and we already have an issue to track the null stuff.

**Comment by dereuromark** [comment]
Sure. I will just wait for https://github.com/cakephp/phinx/pull/1842 to also land in that bugfix release then.

**Pull request merged**
